// crates/ariadne-parser/fixtures/svelte/sample.svelte
<script lang="ts">
  import Child from './Child.svelte';

  export let title: string;

  let count: number = 0;

  $: doubled = count * 2;

  function increment(): void {
    count += 1;
  }
</script>

<div class="card">
  <h1>{title}</h1>
  <Child label={doubled} />
  {#if count > 0}
    <p>positive</p>
  {/if}
  <button onclick={increment}>add</button>
</div>

<style>
  .card {
    padding: 1rem;
  }
</style>

// crates/ariadne-parser/fixtures/vue/sample.vue
<template>
  <div class="card">
    <h1>{{ title }}</h1>
    <Child :label="title" @select="onSelect" />
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import Child from './Child.vue'

const props = defineProps<{ title: string }>()
const count = ref(0)

function onSelect(id: number): void {
  count.value = id
}
</script>

<style scoped>
.card {
  padding: 1rem;
}
</style>
